name: Test Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # we are using --force so that mismatching peer dependencies is ignored
    - name: Install dependencies
      run: npm install --force

    # ref: https://github.com/cypress-io/github-action
    - name: Setup cypress
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        headless: true

    - name: Run the tests and generate coverage report
      run: npm run full-test 

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.13